// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) HINAWA_FW_FCP_ERROR_ABORTED);
    PRINT_CONSTANT((gint) HINAWA_FW_FCP_ERROR_LARGE_RESP);
    PRINT_CONSTANT((gint) HINAWA_FW_FCP_ERROR_TIMEOUT);
    PRINT_CONSTANT((gint) HINAWA_FW_NODE_ERROR_DISCONNECTED);
    PRINT_CONSTANT((gint) HINAWA_FW_NODE_ERROR_FAILED);
    PRINT_CONSTANT((gint) HINAWA_FW_NODE_ERROR_NOT_OPENED);
    PRINT_CONSTANT((gint) HINAWA_FW_NODE_ERROR_OPENED);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_ADDRESS_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_BUSY);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_CANCELLED);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_COMPLETE);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_CONFLICT_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_DATA_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_GENERATION);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_INVALID);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_NO_ACK);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_SEND_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_RCODE_TYPE_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_ADDRESS_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_BUSY);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_CANCELLED);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_CONFLICT_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_DATA_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_GENERATION);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_INVALID);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_NO_ACK);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_SEND_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_REQ_ERROR_TYPE_ERROR);
    PRINT_CONSTANT((gint) HINAWA_FW_RESP_ERROR_ADDR_SPACE_USED);
    PRINT_CONSTANT((gint) HINAWA_FW_RESP_ERROR_FAILED);
    PRINT_CONSTANT((gint) HINAWA_FW_RESP_ERROR_RESERVED);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_CYCLE_START);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_BOUNDED_ADD);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_COMPARE_SWAP);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_FETCH_ADD);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_LITTLE_ADD);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_MASK_SWAP);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_REQUEST);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_RESPONSE);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_VENDOR_DEPENDENT);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_LOCK_WRAP_ADD);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_READ_BLOCK_REQUEST);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_READ_BLOCK_RESPONSE);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_READ_QUADLET_REQUEST);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_READ_QUADLET_RESPONSE);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_STREAM_DATA);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_WRITE_BLOCK_REQUEST);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_WRITE_QUADLET_REQUEST);
    PRINT_CONSTANT((gint) HINAWA_FW_TCODE_WRITE_RESPONSE);
    return 0;
}
