// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "HinawaFwFcp", sizeof(HinawaFwFcp), alignof(HinawaFwFcp));
    printf("%s;%zu;%zu\n", "HinawaFwFcpClass", sizeof(HinawaFwFcpClass), alignof(HinawaFwFcpClass));
    printf("%s;%zu;%zu\n", "HinawaFwFcpError", sizeof(HinawaFwFcpError), alignof(HinawaFwFcpError));
    printf("%s;%zu;%zu\n", "HinawaFwNode", sizeof(HinawaFwNode), alignof(HinawaFwNode));
    printf("%s;%zu;%zu\n", "HinawaFwNodeClass", sizeof(HinawaFwNodeClass), alignof(HinawaFwNodeClass));
    printf("%s;%zu;%zu\n", "HinawaFwNodeError", sizeof(HinawaFwNodeError), alignof(HinawaFwNodeError));
    printf("%s;%zu;%zu\n", "HinawaFwRcode", sizeof(HinawaFwRcode), alignof(HinawaFwRcode));
    printf("%s;%zu;%zu\n", "HinawaFwReq", sizeof(HinawaFwReq), alignof(HinawaFwReq));
    printf("%s;%zu;%zu\n", "HinawaFwReqClass", sizeof(HinawaFwReqClass), alignof(HinawaFwReqClass));
    printf("%s;%zu;%zu\n", "HinawaFwReqError", sizeof(HinawaFwReqError), alignof(HinawaFwReqError));
    printf("%s;%zu;%zu\n", "HinawaFwResp", sizeof(HinawaFwResp), alignof(HinawaFwResp));
    printf("%s;%zu;%zu\n", "HinawaFwRespClass", sizeof(HinawaFwRespClass), alignof(HinawaFwRespClass));
    printf("%s;%zu;%zu\n", "HinawaFwRespError", sizeof(HinawaFwRespError), alignof(HinawaFwRespError));
    printf("%s;%zu;%zu\n", "HinawaFwTcode", sizeof(HinawaFwTcode), alignof(HinawaFwTcode));
    return 0;
}
