// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "HinawaFwFcp", sizeof(HinawaFwFcp), alignof(HinawaFwFcp));
    printf("%s;%zu;%zu\n", "HinawaFwFcpClass", sizeof(HinawaFwFcpClass), alignof(HinawaFwFcpClass));
    printf("%s;%zu;%zu\n", "HinawaFwFcpError", sizeof(HinawaFwFcpError), alignof(HinawaFwFcpError));
    printf("%s;%zu;%zu\n", "HinawaFwNode", sizeof(HinawaFwNode), alignof(HinawaFwNode));
    printf("%s;%zu;%zu\n", "HinawaFwNodeClass", sizeof(HinawaFwNodeClass), alignof(HinawaFwNodeClass));
    printf("%s;%zu;%zu\n", "HinawaFwNodeError", sizeof(HinawaFwNodeError), alignof(HinawaFwNodeError));
    printf("%s;%zu;%zu\n", "HinawaFwRcode", sizeof(HinawaFwRcode), alignof(HinawaFwRcode));
    printf("%s;%zu;%zu\n", "HinawaFwReq", sizeof(HinawaFwReq), alignof(HinawaFwReq));
    printf("%s;%zu;%zu\n", "HinawaFwReqClass", sizeof(HinawaFwReqClass), alignof(HinawaFwReqClass));
    printf("%s;%zu;%zu\n", "HinawaFwResp", sizeof(HinawaFwResp), alignof(HinawaFwResp));
    printf("%s;%zu;%zu\n", "HinawaFwRespClass", sizeof(HinawaFwRespClass), alignof(HinawaFwRespClass));
    printf("%s;%zu;%zu\n", "HinawaFwRespError", sizeof(HinawaFwRespError), alignof(HinawaFwRespError));
    printf("%s;%zu;%zu\n", "HinawaFwTcode", sizeof(HinawaFwTcode), alignof(HinawaFwTcode));
    printf("%s;%zu;%zu\n", "HinawaSndDg00x", sizeof(HinawaSndDg00x), alignof(HinawaSndDg00x));
    printf("%s;%zu;%zu\n", "HinawaSndDg00xClass", sizeof(HinawaSndDg00xClass), alignof(HinawaSndDg00xClass));
    printf("%s;%zu;%zu\n", "HinawaSndDice", sizeof(HinawaSndDice), alignof(HinawaSndDice));
    printf("%s;%zu;%zu\n", "HinawaSndDiceClass", sizeof(HinawaSndDiceClass), alignof(HinawaSndDiceClass));
    printf("%s;%zu;%zu\n", "HinawaSndDiceError", sizeof(HinawaSndDiceError), alignof(HinawaSndDiceError));
    printf("%s;%zu;%zu\n", "HinawaSndEfw", sizeof(HinawaSndEfw), alignof(HinawaSndEfw));
    printf("%s;%zu;%zu\n", "HinawaSndEfwClass", sizeof(HinawaSndEfwClass), alignof(HinawaSndEfwClass));
    printf("%s;%zu;%zu\n", "HinawaSndEfwStatus", sizeof(HinawaSndEfwStatus), alignof(HinawaSndEfwStatus));
    printf("%s;%zu;%zu\n", "HinawaSndMotu", sizeof(HinawaSndMotu), alignof(HinawaSndMotu));
    printf("%s;%zu;%zu\n", "HinawaSndMotuClass", sizeof(HinawaSndMotuClass), alignof(HinawaSndMotuClass));
    printf("%s;%zu;%zu\n", "HinawaSndMotuRegisterDspParameter", sizeof(HinawaSndMotuRegisterDspParameter), alignof(HinawaSndMotuRegisterDspParameter));
    printf("%s;%zu;%zu\n", "HinawaSndTscm", sizeof(HinawaSndTscm), alignof(HinawaSndTscm));
    printf("%s;%zu;%zu\n", "HinawaSndTscmClass", sizeof(HinawaSndTscmClass), alignof(HinawaSndTscmClass));
    printf("%s;%zu;%zu\n", "HinawaSndUnit", sizeof(HinawaSndUnit), alignof(HinawaSndUnit));
    printf("%s;%zu;%zu\n", "HinawaSndUnitClass", sizeof(HinawaSndUnitClass), alignof(HinawaSndUnitClass));
    printf("%s;%zu;%zu\n", "HinawaSndUnitError", sizeof(HinawaSndUnitError), alignof(HinawaSndUnitError));
    printf("%s;%zu;%zu\n", "HinawaSndUnitType", sizeof(HinawaSndUnitType), alignof(HinawaSndUnitType));
    return 0;
}
