[package]
name = "hinawa"
version = "0.1.0"
description = "API bindings for libhinawa2 library"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]

[lib]
name = "hinawa"

[dependencies]
libc = "0.2"
glib = { git = "https://github.com/gtk-rs/glib" }
glib-sys = { git = "https://github.com/gtk-rs/sys" }
gobject-sys = { git = "https://github.com/gtk-rs/sys" }
hinawa-sys = { path = "../hinawa-sys" }

[dev-dependencies]
gir-format-check = "^0.1"
