[package]
name = "hinawa"
version = "0.5.1"
description = "API bindings for libhinawa2 library"
authors = ["Takashi Sakamoto <o-takashi@sakamocchi.jp>"]
license = "MIT"
repository = "https://github.com/alsa-project/hinawa-rs/"

[lib]
name = "hinawa"

[dependencies]
libc = "0.2"

glib = "0.10"
glib-sys = "0.10"
gobject-sys = "0.10"

hinawa-sys = { path = "../hinawa-sys", version = "0.5" }

[dev-dependencies]
gir-format-check = "^0.1"
