[options]
girs_directories = ["../gir-files", ".."]
work_mode = "normal"
library = "Hinawa"
version = "3.0"
use_gi_docgen = true
min_cfg_version = "2.5"
deprecate_by_min_version = true
single_version_file = true

generate = [
    "Hinawa.FwRcode",
    "Hinawa.FwTcode",
    "Hinawa.FwNodeError",
    "Hinawa.FwReqError",
    "Hinawa.FwRespError",
    "Hinawa.FwFcpError",
]

manual = [
    "GLib.Error",
    "GLib.Source",
]

[[object]]
name = "Hinawa.FwNode"
status = "generate"
manual_traits = ["FwNodeExtManual"]
    [[object.function]]
    pattern = "get_config_rom"
    ignore = true
    doc_trait_name = "FwNodeExtManual"

[[object]]
name = "Hinawa.FwReq"
status = "generate"
manual_traits = ["FwReqExtManual"]
    [[object.signal]]
    pattern = "responded"
    ignore = true
    doc_trait_name = "FwReqExtManual"
    [[object.function]]
    pattern = "transaction_async"
    ignore = true
    doc_trait_name = "FwReqExtManual"
    [[object.function]]
    pattern = "transaction_sync"
    ignore = true
    doc_trait_name = "FwReqExtManual"
    [[object.function]]
    pattern = "transaction"
    ignore = true
    doc_trait_name = "FwReqExtManual"
    [[object.function]]
    pattern = "error_quark"
    ignore = true

[[object]]
name = "Hinawa.FwResp"
status = "generate"
manual_traits = ["FwRespExtManual"]
    [[object.function]]
    pattern = "get_req_frame"
    ignore = true
    doc_trait_name = "FwRespExtManual"
    [[object.signal]]
    pattern = "requested2"
    ignore = true
    doc_trait_name = "FwRespExtManual"

[[object]]
name = "Hinawa.FwFcp"
status = "generate"
manual_traits = ["FwFcpExtManual"]
    [[object.function]]
    pattern = "avc_transaction"
    ignore = true
    doc_trait_name = "FwFcpExtManual"
    [[object.function]]
    pattern = "transaction"
    ignore = true
    doc_trait_name = "FwFcpExtManual"
    [[object.signal]]
    pattern = "responded"
    ignore = true
    doc_trait_name = "FwFcpExtManual"
