// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::translate::*;
use std::fmt;

glib::wrapper! {
    #[doc(alias = "HinawaFwReq")]
    pub struct FwReq(Object<ffi::HinawaFwReq, ffi::HinawaFwReqClass>);

    match fn {
        type_ => || ffi::hinawa_fw_req_get_type(),
    }
}

impl FwReq {
    pub const NONE: Option<&'static FwReq> = None;

    #[doc(alias = "hinawa_fw_req_new")]
    pub fn new() -> FwReq {
        unsafe { from_glib_full(ffi::hinawa_fw_req_new()) }
    }
}

impl Default for FwReq {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for FwReq {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("FwReq")
    }
}
