// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use crate::SndUnit;
use glib::object::Cast;
use glib::object::IsA;
use glib::signal::connect_raw;
use glib::signal::SignalHandlerId;
use glib::translate::*;
use std::boxed::Box as Box_;
use std::fmt;
use std::mem::transmute;
use std::ptr;

glib::wrapper! {
    #[doc(alias = "HinawaSndDg00x")]
    pub struct SndDg00x(Object<ffi::HinawaSndDg00x, ffi::HinawaSndDg00xClass>) @extends SndUnit;

    match fn {
        type_ => || ffi::hinawa_snd_dg00x_get_type(),
    }
}

impl SndDg00x {
    pub const NONE: Option<&'static SndDg00x> = None;

    #[doc(alias = "hinawa_snd_dg00x_new")]
    pub fn new() -> SndDg00x {
        unsafe { from_glib_full(ffi::hinawa_snd_dg00x_new()) }
    }
}

impl Default for SndDg00x {
    fn default() -> Self {
        Self::new()
    }
}

pub trait SndDg00xExt: 'static {
    #[doc(alias = "hinawa_snd_dg00x_open")]
    fn open(&self, path: &str) -> Result<(), glib::Error>;

    #[doc(alias = "message")]
    fn connect_message<F: Fn(&Self, u32) + 'static>(&self, f: F) -> SignalHandlerId;
}

impl<O: IsA<SndDg00x>> SndDg00xExt for O {
    fn open(&self, path: &str) -> Result<(), glib::Error> {
        unsafe {
            let mut error = ptr::null_mut();
            let _ = ffi::hinawa_snd_dg00x_open(
                self.as_ref().to_glib_none().0,
                path.to_glib_none().0,
                &mut error,
            );
            if error.is_null() {
                Ok(())
            } else {
                Err(from_glib_full(error))
            }
        }
    }

    fn connect_message<F: Fn(&Self, u32) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn message_trampoline<P: IsA<SndDg00x>, F: Fn(&P, u32) + 'static>(
            this: *mut ffi::HinawaSndDg00x,
            message: libc::c_uint,
            f: glib::ffi::gpointer,
        ) {
            let f: &F = &*(f as *const F);
            f(SndDg00x::from_glib_borrow(this).unsafe_cast_ref(), message)
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(
                self.as_ptr() as *mut _,
                b"message\0".as_ptr() as *const _,
                Some(transmute::<_, unsafe extern "C" fn()>(
                    message_trampoline::<Self, F> as *const (),
                )),
                Box_::into_raw(f),
            )
        }
    }
}

impl fmt::Display for SndDg00x {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str("SndDg00x")
    }
}
