[options]
girs_directories = ["../gir-files", ".."]
work_mode = "sys"
library = "Hinawa"
version = "3.0"
min_cfg_version = "2.4"
single_version_file = "."
external_libraries = [
  "GLib",
  "GObject",
]
